Added option to have zshrc with plugins already enabled.
ministryofjustice/linuxify pull request #9
Opened 2024-10-15 12:46 UTC by smjmoj

for oh-my-zsh if installed

2024-10-15 12:59 UTC, laurentb4 approved these changes
LGTM

2024-10-15 13:15 UTC, AafAnsari requested changes

2024-10-15 13:15 UTC, AafAnsari commented on shell_rc_alias_files/zshrc_ohmyzsh
> +echo 'LOADED .zshrc'
`echo 'LOADED .zshrc'` can be removed. It will be duplicated

2024-10-16 14:39 UTC, AafAnsari approved these changes

2024-10-16 14:40 UTC, merged